version: '2'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - sample_db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sample_db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - mynet

  sample_db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=product_db
      - POSTGRES_PORT=5432
    volumes:
      - sample_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynet

networks:
  mynet:
    name: my-shared-db-network

volumes:
  sample_db:
